apiVersion: v1
kind: PersistentVolume
metadata:
  name: devops-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/docker       # on minikube
    type: DirectoryOrCreate
